on:
  push:
    branches:
      - develop
name: Deploy Develop
jobs:
  web-deploy:
    name: 🎉 Deploy
    runs-on: ubuntu-latest
    steps:
    - name: 🚚 Get latest code
      uses: actions/checkout@v2
    
    - name: 📂 Sync files
      uses: SamKirkland/FTP-Deploy-Action@4.3.3
      with:
        server: ftp.gustavocerqueira.com.br
        username: pote-de-mana@pote-de-mana.gustavocerqueira.com.br
        password: ${{ secrets.develop_ftp_password }}
        local-dir: ./
        server-dir: ./

on:
  workflow_run:
    workflows: [Deploy Develop]
    types: [completed]

jobs:
  on-success:
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    steps:
      - name: Test Custom
        uses: rjstone/discord-webhook-notify@v1
        with:
            severity: info
            username: GithubActions
            color: '#0F0'
            avatarUrl: https://github.githubassets.com/images/modules/logos_page/Octocat.png
            description: "Status: Sucesso"
            details: Deploy finalizado.
            footer: Pote de Mana.
            text: ${{ github.event.workflow.name }}
            webhookUrl: ${{ secrets.discord_webhook }}
  on-failure:
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'failure' }}
    steps:
      - run: echo 'The triggering workflow failed'